server:
  port: 9000

spring:
  application:
    name: Basic-Auth-Backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/basic_auth?autoReconnect=true&failOverReadOnly=false&maxReconnects=10}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:my_secret_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


app:
  jwtSecret: bezKoderSecretKey
  jwtExpirationMs: 8640000
